### ISSUE TITLE
High typing latency compared to traditional shells

### ISSUE THREAD

**Issue by comex** [nushell/nushell#10484]
### Describe the bug

After typing a character, nushell takes 10-14ms to echo back that same character to the terminal output.

That might not seem like much, but zsh and bash do it in less than 1ms.  10-14ms will typically delay display output by at least one frame, depending on your frame rate.  Also, for some reason, this delay is amplified when using Terminal.app (I'll post a separate comment about this), making it quite noticeable.

### How to reproduce

Download this script I wrote: [shell-latency-test.py](https://gist.github.com/comex/fd9748146ad838855d5a9d4b664aa603)

The script should work on macOS and Linux.  It spawns a shell in a pty, waits for it to be finished initializing, then inputs a few letters and waits for those letters to be echoed back to the output.

Output on my machine (MacBook Pro M1):
```
% python3 shell-latency-test.py bash -n
[..snip..]
done.  latency: 0.00035881996154785156
% python3 shell-latency-test.py zsh -n 
[..snip..]
done.  latency: 0.0008268356323242188
% python3 shell-latency-test.py nu -n  
[..snip..]
done.  latency: 0.014031171798706055
% nu --version
0.84.0
```
(I also tried this on a different machine, running Linux, using nushell's latest `main`, 6a2fd91a01c17015ad19a6e8960311311cc825de.  The result was similar but a few ms faster.)

### Expected behavior

Moar speed.

### Configuration

```
| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.84.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball) |
| cargo_version      | cargo 1.71.2                                                      |
| build_time         | 2023-08-23 15:47:48 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          |
| features           | default, extra, sqlite, trash, which, zip                         |
| installed_plugins  |                                                                   |
```

**Comment by fdncred** [comment]
This is what I see on 0.85.1 on my mac.
```
> python3 shell-latency-test.py nu -n --no-std-lib
read: b'\x1b[?2004h'
read: b'\x1b[6n'
read: b'\x1b[?25l\x1b[1;1H\x1b[J\x1b[38;5;10m~/src/nushell\x1b[38;5;14m> \x1b[38;5;5m\x1b7\x1b[1;59H09/23/2023 07:30:38 PM\x1b8\x1b[0m\x1b[0m\x1b7\x1b8\x1b[?25h'
read: b'\x1b[?25l\x1b[1;1H\x1b[J\x1b[38;5;10m~/src/nushell\x1b[38;5;14m> \x1b[38;5;5m\x1b7\x1b[1;59H09/23/2023 07:30:39 PM\x1b8\x1b[0m\x1b[0m\x1b[36mEzhJinYrBT\x1b[0m\x1b7\x1b8\x1b[?25h'
done.  latency: 0.012382030487060547
```

**Comment by comex** [comment]
More about Terminal.app latency:

Here are the tools I'm using to measure it (which should theoretically work with any terminal and any shell on macOS):
- [`terminal-latency-test.swift`](https://gist.github.com/comex/cc6b3df7217f698b9017b97a56a3ea5b#file-terminal-latency-test-swift) measures the 'end-to-end' terminal latency using keylogging and screen capture.
- [`nusimulator2.py`](https://gist.github.com/comex/cc6b3df7217f698b9017b97a56a3ea5b#file-nusimulator2-py) is a script you can use as a measurement target instead of an actual shell, to minimize the number of variables.  It simply reads input and echoes back some output to the terminal, with an option to sleep 12ms before echoing back.

On my machine, when running `nusimulator2.py` without the 12ms sleep, the latency reported by `terminal-latency-test.swift` is consistently under 20ms.  But with the sleep, it's usually over 70ms.  So the visible difference is 50ms even though the sleep amount is 12ms.

This behavior doesn't appear in kitty or iTerm2.  With both of those terminals, the difference between the average latency with vs. without the 12ms sleep is on the order of 12ms.  (I didn't bother measuring it exactly, but it's nowhere near 50ms.)

Other potential causes ruled out:
- It's not because the sleep is getting prolonged compared to the requested amount.  `nusimulator2.py` measures the actual time before and after the sleep; the sleep does get prolonged, but only by up to ~4ms.
- It isn't an artifact of the screen capture method; I originally saw similar data using an iPhone camera to physically record the screen (along with the [Is It Snappy?](https://isitsnappy.com/) app), before writing the screen to get cleaner resulots.

I am going to file a bug report with Apple.

Still, regardless of what the terminal does, it would be good to fix the latency on nushell's side.  50ms is more noticeable than 12ms, but 12ms is still perceptible.

I do realize that nushell is doing more work than zsh/bash as it's showing inline completions for every keystroke.  I haven't investigated what exactly is taking up time within nushell, but I'm guessing it's the search for completions.  If so, perhaps nushell could echo the user's typed character immediately and fill in the completions asynchronously.

**Comment by fdncred** [comment]
Thanks for all your research. We appreciate your help. I'm just guessing that something is going on in reedline but it may also be in nushell too.

**Comment by comex** [comment]
It turns out this 10ms is an intentional delay in `reedline`:
```rust
// The POLL_WAIT is used to specify for how long the POLL should wait for
// events, to accelerate the handling of paste or compound resize events. Having
// a POLL_WAIT of zero means that every single event is treated as soon as it
// arrives. This doesn't allow for the possibility of more than 1 event
// happening at the same time.
const POLL_WAIT: u64 = 10;
```
If I change it to 0 then the latency goes down to tens of microseconds - problem solved!  Except that the wait is there for a reason, so really what's needed is for `reedline` to choose a wait time more dynamically.  I will file an issue against `reedline`.

By the way, [here is a better test script](https://gist.github.com/comex/380653fefb3312b24da5d66ed5ee5be0) that does repeated tests rather than just one.

**Comment by fdncred** [comment]
It would be great to have a more dynamic `POLL_WAIT`. Would love to see a PR from you with a creative heuristic for that.

**Comment by YizhePKU** [comment]
https://github.com/nushell/reedline/pull/846 has landed, which should solve the typing latency issue. I'm getting sub-millisecond latency using the test scripts.

**Comment by fdncred** [comment]
Thanks

**Comment by Feel-ix-343** [comment]
It's still noticably higher than zsh. Might there be more work here?

**Comment by ShadiKhoury-nv** [comment]
Still see high latency compared to traditional shells . if vm has 4 cores
