### ISSUE TITLE
Env variables should be available at parse time or `source(-env)` should accept them

### ISSUE THREAD

**Issue by poliorcetics** [nushell/nushell#10505]
### Related problem

In my config I wanted to do:

```nu
source-env $"($env.HOME)/.config/nushell/defaults/env.nu"
```

To make it multiplatform easily

I got the error:

```
Value is not a parse-time constant
help: Only a subset of expressions are allowed constants during parsing. Try using the 'const' command or typing the value literally.
```

## Solution 1

All defined environment variables should be available at parse time.

I think a reasonable limitation is:

```nu
# $env.TEST defined to anything that is not 42 or 43
$env.TEST = 43
const A = $env.TEST
$env.TEST = 42
const B = $env.TEST
use assert
assert ($A == $B) # Should pass
```

That is, env var in consts are are never affected by anything in the script

## Solution 2

`source` and `source-env` should either have a way to tell "source this file relative to the current nu script, not the current directory" or be able to const-interpret env vars to achieve the same effect

### Additional context and details

With solution 1 I worry `source-env $"($env.HOME)/.config/nushell/defaults/env.nu"` would be unclear as to when the variable is evaluated so I think, if that solution is taken, only `const NAME = ...` should accept const-time interpretation of env vars for now. That can always be relaxed later if people don't think this is a problem

**Comment by poliorcetics** [comment]
Related to #10239

**Comment by fdncred** [comment]
I'm wondering if this error is just because you're trying to use `$env.HOME` with a source command. What if you did something like this:
```nushell
source-env ~/.config/nushell/defaults/env.nu
```

or constructed a const like

```nushell
const HOMEY = if blah { "/some/constant/path" } else { "/some/other/constant/path" }
source-env $HOMEY
```

**Comment by poliorcetics** [comment]
> `source-env ~/.config/nushell/defaults/env.nu`

I'm dumb and should have tried this before. Sorry for that

Still, I think being able to use predefined env vars in const-context would be nice, but since my use case is fixed, do you want me to close this issue ?

**Comment by kubouch** [comment]
Env vars being available in parse-time evaluation is a subtle footgun because they are updated at runtime which is not available at parse time.

Consider this (`>` denotes different REPL lines)
```nushell
> $env.SPAM = '/path/to/old/spam.nu'

> $env.SPAM = '/path/to/new/spam.nu'; use $env.SPAM
```
The second line would be trying to `use /path/to/old/spam.nu`.

We still have this problem with current directory (e.g., `cd spam; use ./spam.nu` doesn't load `spam/spam.nu`) but that's pretty much unavoidable. I'd rather not propagate this further.

**Comment by poliorcetics** [comment]
yes that's what I mentioned in the last section of the initial message, where I propose forcing such evaluation only in `const`, where at least there can be an indicator

**Comment by kubouch** [comment]
Yeah, I think it would still be subtle enough to cause problems. I'm not saying we'll never support it, but we must be VERY careful about allowing env vars in const eval.

**Comment by cloudhan** [comment]
This is unavailable, which is also quite annoying...

```nushell
use $'($env.FILE_PWD)/my_config.nu'
```

**Comment by kubouch** [comment]
`use my_config.nu` uses file-relative path by default, it's not necessary to prepend `$env.FILE_PWD`.

But regardless of that, I believe many values from `$env`, like `FILE_PWD` could be moved to const.

**Comment by cloudhan** [comment]
Not exactly, in the `config.nu`, with `use my_config.nu`

cd to `AppData\Roaming\nushell` (the dirname of $nu.config-path), it loads fine,

but then in AppData\Roaming` 

```
  × Module not found.
     ╭─[C:\Users\cloud\AppData\Roaming\nushell\config.nu:767:1]
 767 │ # https://github.com/nushell/nushell/issues/4662#issuecomment-1387377806
 768 │ use my_config.nu
     ·     ─────────┬────────
     ·              ╰── module not found
```

**Comment by cloudhan** [comment]
For latter comers, to allow the loading, follow https://github.com/nushell/nushell/issues/4662#issuecomment-1387377806, `NU_LIB_DIRS` needs to be modified.

IMHO, for a shell, it should not be these strict, it should be more dynamic without the concepts like parsing time.
These type of problems (strongly opinionated design) immediately turn away new users.

**Comment by kubouch** [comment]
> Not exactly, in the `config.nu`, with `use my_config.nu`
> 
> cd to `AppData\Roaming\nushell` (the dirname of `$nu.config-path`), it loads fine,
> 
> but then in `AppData\Roaming`
> 
> ```
>   × Module not found.
>      ╭─[C:\Users\cloud\AppData\Roaming\nushell\config.nu:767:1]
>  767 │ # https://github.com/nushell/nushell/issues/4662#issuecomment-1387377806
>  768 │ use my_config.nu
>      ·     ─────────┬────────
>      ·              ╰── module not found
> ```

If that file sits right next to `config.nu`, then this looks like a bug. We might not be setting the current file path directory properly when loading the config.

**Comment by kubouch** [comment]
That won't work fully because the `activate.nu` defines a `deactivate` alias which is a parser definition, it would be scoped. Environment is possible to preserve with `def --env`.

**Comment by dc740** [comment]
I know. I been looking for ways to mitigate it, but even defining my custom functions requires typing several commands.
I can't even create an alias that calls my function and later overlay use, because the alias definition requires the activate.nu file to be accessible.
what I'm doing now is running a function for the setup, I activate the overlay later, start the editor and after the editor is done, run a tear down function, then finally deactivate the overlay. I was used to have all of that automated and I would just run the editor and expect the rest to happen in the background. I guess a workaround would be to actually write a plugin for my editor.

**Comment by sheeldotme** [comment]
This issue is also relevant when using external tools that create ephemeral nu scripts that must then source modules.

In my case, I have a directory of modules in my git repository that I want to source in various just recipes, [just](https://github.com/casey/just) executes these recipes by writing scripts to a temporary file no longer colocated with the repository alongside the modules. Because the git repository's path cannot be predetermined(it could be checked out anywhere) even relative paths will not work so an environment variable to store and access the module path would be a helpful solution.

**Comment by fdncred** [comment]
Have you tried working with `$NU_LIB_DIRS`, which is a const? If a script is in an of the folders present in `$NU_LIB_DIRS` it should be accessible with `source foo.nu` or `use foo.nu`.

`$env` is not thread-safe and can be changed so we don't allow it to be treated as a const.
