### ISSUE TITLE
ls with recursive glob pattern can output empty results

### ISSUE THREAD

**Issue by DoumanAsh** [nushell/nushell#12004]
### Describe the bug

Given following:
```
let folder = (pwd)
ls $"($folder)/**/Cargo.toml"
```

You shall get dozens of empty outputs:
```
╭─────┬──╮
│ 216 │  │
│ 217 │  │
│ 218 │  │
│ 219 │  │
│ 220 │  │
│ 221 │  │
│ 222 │  │
│ 223 │  │
│ 224 │  │
│ 225 │  │
│ 226 │  │
│ 227 │  │
╰─────┴──╯
╭─────┬──╮
│ 228 │  │
│ 229 │  │
│ 230 │  │
│ 231 │  │
│ 232 │  │
│ 233 │  │
│ 234 │  │
│ 235 │  │
│ 236 │  │
│ 237 │  │
╰─────┴──╯
```

As example similar python code would return only matching patterns:
```
>>> len(glob("{}/**/Cargo.toml".format(folder), recursive=True))
279
```

Meanwhile nushell's ls outputs outrageous 1213 which mostly consist of empty lines

### How to reproduce

- Go to the root/home folder where you have somewhere files matching pattern

### Expected behavior

Do not output empty output

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.90.1                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | macos-aarch64                                        |
| build_target       | aarch64-apple-darwin                                 |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (Homebrew)       |
| cargo_version      | cargo 1.75.0                                         |
| build_time         | 2024-02-06 22:28:49 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

**Comment by rtpg** [comment]
As an extra data point, I didn't hit this issue on my machine, running from the `nushell` repo base poitn on the commit tagged `0.90.1`

@DoumanAsh do you have this issue on many folders (for example on a checkout of this repo?)


| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.90.1                                   |
| branch             |                                          |
| commit_hash        | c2992d5d8b8541b64e9fc1440ed2917fc9b757f7 |
| build_os           | macos-aarch64                            |
| build_target       | aarch64-apple-darwin                     |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)      |
| rust_channel       | 1.73.0-aarch64-apple-darwin              |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)      |
| build_time         | 2024-02-28 16:47:16 +09:00               |
| build_rust_channel | debug                                    |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by DoumanAsh** [comment]
@rtpg So in my example I executed it from home folder.
And I only had collection of repositories with Rust code in `~/repos/**`

This only happens when I try to run it from home with multiple directories having none of glob hits

Could you try to run `ls ~/**/Cargo.toml`?

**Comment by DoumanAsh** [comment]
Hmm I'm not sure how to make simplified example (I can really encounter it from the root or home folder on my PC)
Is there some debug logs that I can enable for `ls` with glob?

**Comment by fdncred** [comment]
not that i know of. does the `glob` command give you the same result?

**Comment by DoumanAsh** [comment]
Huh, this is interesting
`glob` gives complete list with only valid results
`ls` gives incomplete result with a lot of empty values:

```
21:58 $ ls ~/**/Cargo.toml
╭───┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 0 │                                                                                                                             │
│ 1 │                                                                                                                             │
│ 2 │                                                                                                                             │
│ 3 │                                                                                                                             │
│ 4 │                                                                                                                             │
│ 5 │ ╭──────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │
│   │ │ name     │ C:\Users\Douman\AppData\Local\Pub\Cache\hosted\pub.dev\super_native_extensions-0.4.0\cargokit\build_tool\Car │ │
│   │ │          │ go.toml                                                                                                      │ │
│   │ │ type     │ file                                                                                                         │ │
│   │ │ size     │ 363 B                                                                                                        │ │
│   │ │ modified │ 8 months ago                                                                                                 │ │
│   │ ╰──────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰───┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭───┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 6 │ ╭──────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │
│   │ │ name         │ C:\Users\Douman\AppData\Local\Pub\Cache\hosted\pub.dev\super_native_extensions-0.4.0\rust\Cargo.toml     │ │
│   │ │ type         │ file                                                                                                     │ │
│   │ │ size         │ 2.6 KiB                                                                                                  │ │
│   │ │ modified     │ 8 months ago                                                                                             │ │
│   │ ╰──────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│ 7 │                                                                                                                             │
│ 8 │                                                                                                                             │
╰───┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭────┬──╮
│  9 │  │
│ 10 │  │
│ 11 │  │
│ 12 │  │
│ 13 │  │
│ 14 │  │
│ 15 │  │
│ 16 │  │
│ 17 │  │
│ 18 │  │
│ 19 │  │
│ 20 │  │
╰────┴──╯
```

It seems `glob` can be used in place of `ls` much better when you want recursive search

**Comment by fdncred** [comment]
Seems like there's a bug in `ls` somewhere.

**Comment by fdncred** [comment]
I wonder if this because the filesystem is slow and timing out somewhere?

**Comment by DoumanAsh** [comment]
native `find` works quite fast on my SSD so I'm not sure

`ls` doesn't really report errors so I cannot say if there were any OS errors in he midst of it
But considering it doesn't output all possible files I suspect it could be ignoring some results and skipping folders for some reason. Could be due to system errors idk

**Comment by fdncred** [comment]
do the results from `ls` and `glob` match? if so, my guess would be nothing is missing. otherwise, you may be able to narrow it down by seeing what glob reports that ls does not report.

**Comment by rtpg** [comment]
@DoumanAsh are you running on windows or mac? Those file patterns look windows-like but the reported config you posted seems to be from Mac

**Comment by DoumanAsh** [comment]
Sorry, Im at my home PC and there is windows
I can re-try later on Mac to see if `-a` flag makes difference there

**Comment by DoumanAsh** [comment]
@rtpg I did experiment on my Mac

`glob` outputs stably without corrupted up to 1614

```
│ 1613 │ /Users/artur.m/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/panic_abort/Cargo.toml                       │
│ 1614 │ /Users/artur.m/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/sysroot/Cargo.toml                           │
```

Meanwhile `ls` with `-a` option gets me weird output all over the place ending with follwong

```
│ 2278 │ ╭──────────┬─────────────────────────────────────────────────────────────────────────────╮                        │
│      │ │ name     │ /Users/artur.m/repos/personal/rust/tonic/tests/ambiguous_methods/Cargo.toml │                        │
│      │ │ type     │ file                                                                        │                        │
│      │ │ size     │ 382 B                                                                       │                        │
│      │ │ modified │ 5 months ago                                                                │                        │
│      │ ╰──────────┴─────────────────────────────────────────────────────────────────────────────╯                        │
╰──────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by rtpg** [comment]
@DoumanAsh  what if you pipe to `to json`, so `ls -a ... | to json`?  Do you see empty entries in the resulting JSON?

Also would be helpful if any posted output has the command you ran, even if you truncate the output. Just so that reproduction efforts can get a bit more focus

**Comment by DoumanAsh** [comment]
@rtpg Yes, empty values are encoded as explicit `null`

Here is sample https://gist.github.com/DoumanAsh/34047721d48f063959a3b87e59d477d1
I removed file names, but it is the same patterns so its were cargo cache and my personal/work repos

**Comment by rtpg** [comment]
@DoumanAsh if you are able to, would you be able to pull the repo from https://github.com/rtpg/nushell/tree/ls-cleanup, call `cargo run` and run `ls --include-error-details` in a way that causes your issue? This branch should have a _bit_ more information.

**Comment by DoumanAsh** [comment]
Looking at your changes, it seems previously it would just silently ignore errors and return this variant `Value::nothing(call_span)`

Should it actually output empty lines then in first place? 🤔

**Comment by rtpg** [comment]
To be honest I don't think it should, and that it should print out more details. Will make some more changes to the branch to see if we can make this better somehow

**Comment by rtpg** [comment]
@DoumanAsh sorry, could you try this again? I just pushed up some extra changes that should provide more specific error messages (in the `raw` column)

**Comment by DoumanAsh** [comment]
@rtpg Ok, debug info has much more helpful information.
I'm not at my mac, but I imagine it is similar issue:
```
  {
    "type": "error",
    "code": "unknown",
    "details": "Error extracting glob pattern",
    "raw": "GenericError { error: \"Error extracting glob pattern\", msg: \"attempting to read `C:\\\\Users\\\\Douman\\\\AppData\\\\Local\\\\Application Data` resulted in an error: Access is denied. (os error 5)\", span: Some(Span { start: 125704, end: 125706 }), help: None, inner: [] }"
  },

```

It is already late so I will check mac tomorrow

This is definitely not something you need to work around.
So the only issue remains why it outputs empty lines instead of nothing in case of errors? 🤔 
On another side I wonder if it would be good to report error to stderr separately like most unix utilities? (i.e. `find` always prints stderr when you have permission denied)

**Comment by fdncred** [comment]
ya, it would be good to report errors on stderr but keep running i think.

**Comment by rtpg** [comment]
For me I think it's worth having it within the data stream, so that code could see that errors have occurred. Like wouldn't you want to know that some files aren't being treated in your bulk process for example.

There's also an idea of an error sidecar maybe? Maybe this is more a discussion that happens at a higher level

**Comment by fdncred** [comment]
I think it's fine to report errors, even inline, but I don't like the current solution of adding additional columns.

**Comment by DoumanAsh** [comment]
If there would be way to report error, then I assume it would be ok to return `None` here?
Because otherwise user going to continue getting empty lines
Like I can filter it out, but it is pretty weird to get output that has nothing to do with your glob pattern
https://github.com/nushell/nushell/blob/main/crates/nu-command/src/filesystem/ls.rs#L300

**Comment by rtpg** [comment]
Yeah that's why I'm kind of interested in the error sidecar. Maybe a bonus thing would be something "set -eou pipefail"-like that would somehow enforce checking of error objects if the error exists...
