### ISSUE TITLE
Windows Executable Symlinks don't run

### ISSUE THREAD

**Issue by charlespierce** [nushell/nushell#1541]
**Describe the bug**
When trying to run a Windows Executable via a Symlink, instead of running the linked-to executable, NuShell gives an error message: `error: Command not found`

**To Reproduce**
1. Create a symlink in the current directory that links to a valid executable on the system (this may require Administrator privileges).
2. Attempt to call that executable from NuShell.
3. Observe the error.

**Expected behavior**
Calling an executable through a symlink calls the linked-to executable.

**Configuration (please complete the following information):**
 - OS: Windows
 - Version: 0.12.0
 - Optional features (if any): None (used zip file from GH Releases)

**Comment by thegedge** [comment]
Do you know if this worked in a previous version? If so, I may have broken this in https://github.com/nushell/nushell/pull/1535.

**Comment by charlespierce** [comment]
@thegedge I don't know for sure if it worked in a previous version, but @jonathandturner indicated that it did on Discord, and suggested that it might have been a regression.

**Comment by charlespierce** [comment]
@thegedge It may be a result of that PR. It looks like the `ichwh` crate on Windows assumes that anything that isn't a file (which includes a symlink, per the [FileType documentation](https://doc.rust-lang.org/std/fs/struct.FileType.html)) can't be executable (and thus it won't return any symlinks as part of the `which` operation: https://gitlab.com/avandesa/ichwh-rs/-/blob/master/src/windows.rs#L43

**Comment by charlespierce** [comment]
@thegedge Just did a quick test, and it _does_ work correctly in Nushell 0.11.0, so it appears to be a regression between 0.11.0 and 0.12.0.

**Comment by thegedge** [comment]
Thanks for investigating, @charlespierce.

@jonathandturner sounds like this may have been why `which` was used instead of `ichwh`? Perhaps we can still make it work with `ichwh`, but if not, we should probably pick one or the other. We can upstream the necessary fixes to make things work cross platform 🙂

**Comment by jonathandturner** [comment]
I've filed a PR with `ichwh` which should help with this issue.  https://gitlab.com/avandesa/ichwh-rs/-/merge_requests/1

**Comment by jonathandturner** [comment]
cc @avandesa who created `ichwh`. Can you help us with this?

**Comment by avandesa** [comment]
Hey, I just merged the PR and am working on a release. Really sorry about the delay, gitlab didn't notify me there was a PR.

**Comment by avandesa** [comment]
`ichwh-0.3.2` is published. Let me know how else I can help.

**Comment by jonathandturner** [comment]
@avandesa - thanks!

**Comment by jonathandturner** [comment]
@avandesa - not sure if you'll see, but I also submitted a related issue: https://gitlab.com/avandesa/ichwh-rs/-/issues/2

**Comment by charlespierce** [comment]
Just confirmed this still happens on Nu 0.17.0 (which is using the updated `ichwh`). From looking at the linked merge request, I'm actually not sure if that change had an effect. From the docs for [is_symlink](https://doc.rust-lang.org/std/fs/struct.FileType.html#method.is_symlink), it calls out that if the metadata is fetched using `File::metadata`, then `is_symlink` will always be `false`. So I suspect the root cause here might be more difficult to track down.

**Comment by fdncred** [comment]
#2035 is what fixed `winget` which is an `AppExeCLink` according to powershell. `AppExeCLink` is neither a SymbolicLink nor a HardLink nor a Junction. I'm guessing `AppExeCLink` = `ReparsePoint`. That was fixed in the which-rs crate.

[This ](https://github.com/harryfei/which-rs/blob/209804c363b65c1c7cd05d421dbb4510cccae890/src/checker.rs#L42-L47)is what I added to which-rs. It appears that something similar needs to be added to `ichwh`.

**Comment by charlespierce** [comment]
@fdncred It looks like that change in `which-rs` is actually involved in this: By pulling `symlink_metadata` and checking for `is_file`, actual `symlinks` are excluded (because `symlink_metadata` doesn't follow symlinks, so `is_file` would return `false` while `is_symlink` would return `true`). I _think_ the fix would be to update `which` to check `is_file` _or_ `is_symlink` in that spot. I'll confirm that tonight and look at making a PR to implement that fix

**Comment by fdncred** [comment]
Just so I can quit having to look it up in which-rs it's this [PR](https://github.com/harryfei/which-rs/pull/25)

**Comment by fdncred** [comment]
@charlespierce I think this is finally done. We just need to bump the which-rs crate to 4.0.2. #2321
