### ISSUE TITLE
Add a `--save` flag to `alias`

### ISSUE THREAD

**Issue by sophiajt** [nushell/nushell#1731]
**Is your feature request related to a problem? Please describe.**
The `alias` command allows us to create a nice short-hand command for a longer block or pipeline, which is great. Unfortunately, you currently have to retype what you want to save in the config file.

Let's extend `alias` with a `--save` flag that will save the alias to the config as well.

**Describe the solution you'd like**

We can append the alias the user gives us (minus the `--save` flag) to the list of startup commands in config.  You can see these commands by looking in the "startup" column in the config.  Each of them is a line of text, and these are run when Nu starts up.

There are a couple ways to solve this:

* **Make it work**: Append the string of alias to the list that config uses.  You'll need to load the current "startup" list, or create one if it doesn't exist, append the alias, and then save it back to the config. You can see how to do these steps by reading the "crates/nu-cli/src/commands/config.rs" source.

* **Extra**: If the user saves the same alias multiple times, it will work, but the "startup" list will get dirtied with older copies of the alias.  Here we do the above, but we also remove the old aliases that match the alias we're saving.

**Describe alternatives you've considered**

We could make a part of the config file just for aliases, but we can wait to explore that.  Putting everything in startup makes it easier to discover.

**Comment by 1ntEgr8** [comment]
i can try this one!

**Comment by jonathandturner** [comment]
@1ntEgr8 sure thing. it's yours

**Comment by coolshaurya** [comment]
Shouldn't this be closed as it has been resolved by #1852 ?

**Comment by coolshaurya** [comment]
Shouldn't this be closed as its been fixed by #1852 ?

**Comment by thegedge** [comment]
Not sure if we have the "extra", but we can also open another issue for that 🙂

**Comment by thegedge** [comment]
Closed by https://github.com/nushell/nushell/pull/1852

**Comment by Cody-Duncan** [comment]
This feature is missing in v0.68

**Comment by Victor-N-Suadicani** [comment]
Aliases got updated but this feature is still missing. Could this be reopened?

**Comment by sholderbach** [comment]
I assume this got superseded with the `0.59`/`engine-q` refactor.
I am not sure how compatible this is with the current design of nushell's config. It is now arbitrary code in `config.nu` but at the time was more a descriptive toml file which is trivial to edit and leave in a good state.

In theory we could try to write an alias line to the end of the config but not sure how dangerous that might be. (also assumes the thing you are referencing is in scope at startup)

**Comment by amtoine** [comment]
i wonder what the syntax would be :open_mouth: 
```nushell
alias --save foo = bar
```
```nushell
alias foo = bar --save
```

**Comment by eve-an** [comment]
Hello everyone, I'm interested in tackling this issue as my first contribution to the project. I've looked into it and it seems like a good starting point. Looking forward to contributing :)

@amtoine
```shell
alias --save foo = bar
```
Seems like a good fit. Having a flag on the alias command feels more natural than using '--save' as an option.

**Comment by amtoine** [comment]
@eve-an 
thanks for wanting to jump in :pray: 

however, i've talked with the core team and because this issue is getting quite old and we don't feel that much interest in the feature anymore, we've decided to close it for now :innocent: 

the idea here is to simply edit `config.nu` or something like `aliases.nu` if you have a modular config  :yum:
