### ISSUE TITLE
Set_into command changes order of variables in toml file

### ISSUE THREAD

**Issue by boanergies** [nushell/nushell#4245]
### Describe the bug

I've been playing round trying to permanently set environment variables from the command line. Everytime I run the following command:

```
echo $nu.env | insert PYENV_ROOT [$nu.env.HOME]/.pyenv | config set_into env
```
(side note please tell me the proper way of using environment variables when creating paths, I can't seem to get it to work right)

suddenly my starship prompt would break and I saw the issue was that the set_into changed the order of variables in my toml file from
```
startup = ["mkdir ~/.cache/starship", "starship init nu | save ~/.cache/starship/init.nu", "source ~/.cache/starship/init.nu"]
prompt = "starship_prompt"
```
to
```
prompt = "starship_prompt"
startup = ["mkdir ~/.cache/starship", "starship init nu | save ~/.cache/starship/init.nu", "source ~/.cache/starship/init.nu"]
```
which means the starship prompt throws an error not knowing what the starship prompt is

seems like a bug that it tries to sort things alphabetically. I see it also does this to my env section as well

### How to reproduce

1. run a set_into like in my description
2. see the variables change order

### Expected behavior

I expected just to set my path without a worry of other parts of my file being sorted

### Configuration

| key                | value                                                  |
| ------------------ | ------------------------------------------------------ |
| version            | 0.39.0                                                 |
| build_os           | linux-x86_64                                           |
| rust_version       | rustc 1.56.1 (59eed8a2a 2021-11-01)                    |
| rust_channel       | stable-x86_64-unknown-linux-gnu (default)              |
| cargo_version      | cargo 1.56.0 (4ed5d137b 2021-10-04)                    |
| pkg_version        | 0.39.0                                                 |
| build_time         | 2021-11-05 21:49:58 -05:00                             |
| build_rust_channel | release                                                |
| features           | ctrlc, dataframe, default, rustyline, term, which, zip |
| installed_plugins  | fetch, match, post, ps, sys                            |

**Comment by kubouch** [comment]
This is fixed in the new engine: The config will become a config.nu script and there won't be any `config` commands anymore.

To create a path using a variable or environment variable, there are a couple of options. A generic one (not just for paths) would be string interpolation. For paths, there is `path join` which is cross-platform: `insert PYENV_ROOT ([ $nu.env.HOME .pyenv ] | path join)`

**Comment by jntrnr** [comment]
Just to update the previous example, latest main should let you do:

```
let-env PYENV_ROOT = ($env | update PYENV_ROOT ([ $env.HOME .pyenv ] | path join))
```

As we've moved from using a toml-based config to a script-based config, I'm going to close this. If, after trying out the script-based config in the latest main, you're still having issues, please reopen this issue or file a new one.
