### ISSUE TITLE
Completion definition prevent valid command from executing 

### ISSUE THREAD

**Issue by chtenb** [nushell/nushell#6020]
### Describe the bug

When I use the completion definitions found in `nu_scripts/custom-completions/npm/npm-completions.nu`, that prevents me from running perfectly valid commands.

E.g. if I run `npm` that that gives a parse error

```
❯ npm
Error: nu::parser::missing_positional (link)

  × Missing required positional argument.
   ╭─[entry #1:1:1]
 1 │ npm
   ·    ▲
   ·    ╰── missing command
   ╰────
  help: Usage: npm <command>
```

while that is actually a valid command.

It also prevents operations like `which` to produce helpful output

```
❯ which npm
╭───┬─────┬──────────────────────────┬──────────╮
│ # │ arg │           path           │ built-in │
├───┼─────┼──────────────────────────┼──────────┤
│ 0 │ npm │ Nushell built-in command │ true     │
```

### How to reproduce

Use the npm completion script and run `npm`

### Expected behavior

Apparently the syntax definition prevents nu from parsing the command correctly. I would have expected that this information would only be used for completion/help/info generation. If I have typed a command I would have expected nu to obey it.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.63.0                                          |
| branch             |                                                 |
| commit_hash        | 06cf3fa5ad8c8b1d1351c81ccea59a1f8d588dc9        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29)             |
| pkg_version        | 0.63.0                                          |
| build_time         | 2022-05-25 01:15:47 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
Agreed. Custom Completions need to be tweaked a bit. My way around this, for now, is to do `^npm`.

**Comment by Kangaxx-0** [comment]
Seems like a lot of users feel confused about this.  The reason why the command failed is that the `npm` is being treated as pre-defined `internal` command instead of `external` during `parsing`. This brings us to a question → Regarding the custom commands, by default, should they be `internal` or `external`:  My understanding is they are `external`, the reason is simple - They are not built-in

**Comment by fdncred** [comment]
I think they are their own category as is_custom but you may be right that they could be treated as external. Also custom completions kind of play in this arena too but don't have their own category.

**Comment by CAD97** [comment]
Catching incorrect usage is nice if you can verify that the nu definition is accurate and complete.

It may make sense to default to permissive, but the strict behavior should be available.

A simple syntax option to get a permissive extern is to have a `...` parameter with the semantics of allowing whatever captured content.

**Comment by kubouch** [comment]
This is actually a Nushell problem, but just the completions was written such that it requires the positional argument instead of making it optional. Changing
```
  command: string@"nu-complete npm"
```
to
```
  command?: string@"nu-complete npm"
```
in [the npm definition](https://github.com/nushell/nu_scripts/blob/main/custom-completions/npm/npm-completions.nu) should solve the problem. I'll close this issue as it does not seem to show a problem in Nushell itself.

**Comment by chtenb** [comment]
The npm was an example, this issue is about the general problem as indicated in the title: the fact that completion syntaxes will not always reflect the syntax of all (versions of) a certain tool correctly and how nushell deals with that. Perhaps this issue should stay open until the general problem is addressed in a satisfactory manner?

**Comment by kubouch** [comment]
The issue is worded such that it sounds `npm`-specific. https://github.com/nushell/nushell/pull/7527 will be merged in after the 0.73 release, you're welcome to try it and see if it helps. Unfortunately, "commands are not parsed correctly" and "general problem is addressed" are very generic statements that are not actionable. If you still find some problems, feel free to formulate them concretely, what solutions you'd imagine and open a new issue.

**Comment by chtenb** [comment]
Today I updated my nushell installation and checked this out. I think the behavior has improved a lot! Thanks for that.

However, the example given in the OP still does not work:

```
❯ npm
Error: nu::parser::missing_positional (link)

  × Missing required positional argument.
   ╭─[entry #4:1:1]
 1 │ npm
   ╰────
  help: Usage: npm <command>
```

Is this something that can be fixed in the completion definition here?
https://github.com/nushell/nu_scripts/blob/main/custom-completions/npm/npm-completions.nu

For the record, if I pass something rubbish, the command correctly falls through to npm:

```
❯ npm hello
Unknown command: "hello"

To see a list of supported npm commands, run:
  npm help
```

**Comment by kubouch** [comment]
The `command` should be optional: `command?`.

**Comment by chtenb** [comment]
I will send a pull request to patch it. However, it does seem like the fall-through mechanism introduced in https://github.com/nushell/nushell/pull/7527 could or should be extended to cover this use case?
