### ISSUE TITLE
Tab completion

### ISSUE THREAD

**Issue by mo8it** [nushell/nushell#7202]
### Describe the bug

Tab completion seems to be broken starting with version 0.71.

See this comment: https://fosstodon.org/@jntrnr/109389406197343536

### How to reproduce

1. Open nushell
2. Type `ls ` (with space)
3. Press Tab
4. The completion options appear
5. Press Tab again
6. Nothing happens!
7. Press Shift + Tab
8. Completion moves to last option!

### Expected behavior

Shift + Tab moves in the other direction, but Tab seems to be broken! It should go to the next completion. This was the behavior before version 0.71.

### Configuration

❯ version | transpose key value | to md --pretty
| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.71.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20) |
| pkg_version        | 0.71.0                              |
| build_time         | 2022-11-09 17:52:12 +01:00          |
| build_rust_channel | release                             |
| features           | default, trash, which, zip          |
| installed_plugins  |                                     |

### Additional context

Tried with `--config ""` to ignore my config, but it is the same behavior.

**Comment by kamirr** [comment]
Works on `main` for me.

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.71.1                                   |
| branch             | main                                     |
| commit_hash        | e0577e15f2eb33f646c2778c1bb7e729afc21917 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)      |
| rust_channel       | 1.63.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)      |
| pkg_version        | 0.71.1                                   |
| build_time         | 2022-11-22 23:13:59 +01:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I believe this [is the PR ](https://github.com/nushell/nushell/pull/6802)that changed this functionality. The intent Dan was going for was to have the arrow keys be the menu navigation instead of the tab key by default.

This is how you can circumvent this behavior. Use a keybinding like this one.
```
    {
       name: trigger-completion-menu
       modifier: none
       keycode: tab
       mode: emacs
       event: { 
         until: [
           { send: menu name: completion_menu }
           { send: menunext }
           { edit: complete }
         ]
       }
    }
```
and I have `completion_menu` defined in my `menus` section of the `config.nu` defined this way.
```
    {
      name: completion_menu
      only_buffer_difference: false
      marker: $"(char -u 1f4ce) "
      type: {
          layout: columnar
          columns: 4
          col_width: 20   # Optional value. If missing all the screen width is used to calculate column width
          col_padding: 2
      }
      style: {
          text: { fg: "#33ff00" }
          selected_text: { fg: "#0c0c0c" bg: "#33ff00" attr: b}
          description_text: yellow
      }
    }
```

**Comment by Mo8it** [comment]
Using Tab to navigate is like using Alt + Tab to navigate in the desktop. It is something natural for almost every terminal user. I don't think that it is something that people have to configure.
Also: Why does Shift + Tab work? It is not even consistent.
Please revert that change then. Thanks a lot!

**Comment by fdncred** [comment]
Clearly your opinion is not the only opinion otherwise it would've never changed. 

FWIW, I agree with you and I think this one line change should be reverted. However, I was trying to point out to you that it could be configured to act like you want it to now so you don't have to wait and see if it eventually gets reverted or not.

**Comment by Mo8it** [comment]
Sorry if I was harsh. Thanks for helping ❤️

**Comment by sholderbach** [comment]
I think the core intent of the underlying change was to support filling common prefixes while avoiding the surprising automatic completion of everything should your typing narrow the search space, but I think the broken `Tab` action is just an artifact of landing the config changes. We should resolve that first (and then polish the underlying completion setup) but I think reverting the change would cause another regression.

**Comment by valpackett** [comment]
IMO instead of the surprising automatic completion, the default should be like how most shells work: "if there's only one result available, Tab completes, otherwise Tab completes up to the common prefix and then cycles".

The keybinding thing above gets closer to that than ever before! Except for doing things when the menu is already open and you're typing more.

**Comment by amtoine** [comment]
i think i'm able to reproduce this in `nushell` version `0.75.1` on bea7ec33c1d0a7d64e50e42d00a941a2f84408c3 :+1:

**Comment by dschrempf** [comment]
Hi! Cycling with the TAB key is still not working. For example `cd f <TAB>` will not cycle through `folder1`, `folder2`, etc. I am using the `vi` mode.

**Comment by amtoine** [comment]
just built the latest revision but this does not work on my end :thinking: 
<details>
<summary>my config</summary>

should be <code>2a484a3e7</code>...
<code>
╭────────────────────┬──────────────────────────────────────────╮
│ version            │ 0.79.1                                   │
│ branch             │ main                                     │
│ commit_hash        │ 0ea973b78b57bb01ae0b58ecd1c02fda21184043 │
│ build_os           │ linux-x86_64                             │
│ build_target       │ x86_64-unknown-linux-gnu                 │
│ rust_version       │ rustc 1.67.1 (d5a82bbd2 2023-02-07)      │
│ rust_channel       │ 1.67.1-x86_64-unknown-linux-gnu          │
│ cargo_version      │ cargo 1.67.1 (8ecd4f20a 2023-01-10)      │
│ build_time         │ 2023-05-07 10:44:01 +02:00               │
│ build_rust_channel │ release                                  │
│ features           │ default, zip                             │
│ installed_plugins  │                                          │
╰────────────────────┴──────────────────────────────────────────╯
</code>
</details>

**Comment by dschrempf** [comment]
My `config.nu` file is minimal:
```
let-env config = {
  edit_mode: vi
}
```
Could this be the issue? Do we need to configure tab cycling somehow? Maybe I missed something above. Cycling backwards with Shift+TAB works.

**Comment by amtoine** [comment]
@dschrempf 
i'm not sure it has to do with any config :thinking: 
i've tried in `nu --no-config-file` and it does not work :open_mouth:

**Comment by dschrempf** [comment]
Isn't it weird to require special configuration to make tab cycling work?

**Comment by fdncred** [comment]
> Isn't it weird to require special configuration to make tab cycling work?

Not if the default is to use arrow keys.

Having said that, we might should change our default.

**Comment by dschrempf** [comment]
I see! Thanks for your help! Consider my vote on the TAB-cycle side :smile: !

**Comment by dschrempf** [comment]
For reference: Using you menu and keybinding snippet, TAB cycling works.

I also noticed an inconsistency in the keybinding configuration: one list uses commas, the other doesn't. I am aware that both ways are valid syntax, but it is a bit confusing to use both syntaxes right next to each other, isn't it?

**Comment by Abdillah** [comment]
@fdncred In my case adding `{ send: menunext }` config doesn't solve the problem in v0.80.0.

**Comment by fdncred** [comment]
I use tab all the time. I don't understand what the issue is. I use this in my config file.

menu
```
  {
    name: completion_menu
    only_buffer_difference: false
    marker: $"(char -u '1f4ce') "
    type: {
      layout: columnar
      columns: 4
      col_width: 20   # Optional value. If missing all the screen width is used to calculate column width
      col_padding: 2
    }
    style: {
      text: { fg: "#33ff00" }
      selected_text: { fg: "#0c0c0c" bg: "#33ff00" attr: b}
      description_text: yellow
    }
  }
```
keybinding
```
  {
    name: trigger-completion-menu
    modifier: none
    keycode: tab
    mode: [emacs vi_normal vi_insert]
    event: { 
      until: [
        { send: menu name: completion_menu }
        { send: menunext }
        { edit: complete }
      ]
    }
  }
```

**Comment by Abdillah** [comment]
That actually works. But, I have double `let-env` unfortunately. Thanks!

**Comment by Abdillah** [comment]
Also, for everyone, this should works when nushell generate default configuration for us.
The `--no-config-file` indeed remove the tab completion.
And I vote for Tab as default because it has minimal movement (than arrow key).

**Comment by mpizenberg** [comment]
I'd also be interested in having support for tab cycling by default. I like my config files clean and as small as possible.

**Comment by amtoine** [comment]
this missing feature has annoyed me enough :laughing: 
can you check if #10199 solves this? :innocent:
